### ISSUE TITLE
Better error messages!

### ISSUE THREAD

**Issue by ghost** [JulianKemmerer/PipelineC#108]
Right now the various files use sys.exit(-1) in some places, which is less helpful than raising an exception. We should try to make more helpful exception messages, and move towards named and documented exceptions.

**Comment by JulianKemmerer** [comment]
Sounds good - been trying to remember throw exceptions when writing recent code - sounds good.

I have zero ideas for named exceptions - probably need to look at what kinds of things fail and categorize them...
