### ISSUE TITLE
Yosys + GHDL issues

### ISSUE THREAD

**Issue by suarezvictor** [JulianKemmerer/PipelineC#28]
It seems the issue with Yosys and GHDL, as reported by the tools developers, has to do with incorrectly generated code.
https://github.com/ghdl/ghdl-yosys-plugin/issues/158#issuecomment-932159120

I also had issues with pipes and resize commands

**Comment by JulianKemmerer** [comment]
Was able to resolve ghdl yosys plugin issue on their end - see closed issue.
