### ISSUE TITLE
integer division

### ISSUE THREAD

**Issue by suarezvictor** [JulianKemmerer/PipelineC#57]
It would be good that the tools accepts a/b operation even if b is not a float

**Comment by JulianKemmerer** [comment]
Since when does this not work?
 Fp div itself contains and integer divider to work?

Will double check in the morning....

**Comment by JulianKemmerer** [comment]
First thing to double check is that the arguments are actually integers , check for math producing floats ex 1/3 likely converts to fp 0.333... if used in compile time calculation (not integer 0) - would need to add casts to keep integer types

**Comment by JulianKemmerer** [comment]
To be clear this is an issue with specifically signed integers. Unsigned integer division is supported. Just need to 'turn on' signed integer support too...

**Comment by JulianKemmerer** [comment]
Turned on signed division using already working unsigned division
https://github.com/JulianKemmerer/PipelineC/commit/3a357cbffea4b65848a276966e76cc013c97ef79
