### ISSUE TITLE
show progress

### ISSUE THREAD

**Issue by suarezvictor** [JulianKemmerer/PipelineC#61]
when informing `...Waiting on synthesis for: BIN_OP_EQ_uint14_t_uint1_t`,  it would be good to add `function 3/20, elapsed time 01:22` 
that way an estimation of time left to finish can be done...

**Comment by JulianKemmerer** [comment]
-v --verbose could dump every synthesis log to the console (in addition to just log files)

**Comment by JulianKemmerer** [comment]
@suarezvictor You will now see in the time before pipelining iterations, while synthesizing each function
ex. `Function 454/458, elapsed time 0:12:49.686056...`
https://github.com/JulianKemmerer/PipelineC/commit/d9536346fb993ddd008d0607f2484015f4f1c539
