### ISSUE TITLE
Make path delay runs arbitrarily parallelizable 

### ISSUE THREAD

**Issue by JulianKemmerer** [JulianKemmerer/PipelineC#74]
The first half of tool execution is getting path delays for modules.

This should be able to occur in any order / parallel.

Currently however, the tool traverses the module hierarchy up the tree synthesizing bigger and bigger modules as it goes.

This behaves very poorly if there are lots of modules near the top level of the design (ex. if top level has a few-sub wrapper levels, you are essentially sequentially synthesizing the same module over and over...)

Whos got time to wait around - not @suarezvictor :-p

**Comment by suarezvictor** [comment]
Considering that the aim of the tool is "faster development", it seems a bit important

**Comment by JulianKemmerer** [comment]
Also important to note that the second half of tool runtime, iterating on pipelines could also be parallelized...

^good next step after this easier issue is resolved

**Comment by JulianKemmerer** [comment]
Fix in https://github.com/JulianKemmerer/PipelineC/commit/ba7ffc2da4549ba7a8b750a73b05365ec64d2b6a

**Comment by suarezvictor** [comment]
Hi Julian, were you able to measure some gain factors with any specific example?
